import { PrismaClient, CardCategory, AdminRole } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Seed admin user
  const adminEmail = 'admin@cardmatch.com';
  const adminPassword = 'Admin123!';
  const passwordHash = await bcrypt.hash(adminPassword, 10);

  await prisma.admin.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      passwordHash,
      role: AdminRole.SUPER_ADMIN,
    },
  });

  // 1000+ Turkish dating/matching cards
  const cards = [
    // ==================== LIFESTYLE (200) ====================
    { questionTR: 'Sabah kahvaltısında ne olmalı?', category: CardCategory.LIFESTYLE, options: ['Tuzlu', 'Tatlı', 'Her ikisi', 'Kahvaltı yapmam'] },
    { questionTR: 'Tatil tercihin?', category: CardCategory.LIFESTYLE, options: ['Deniz', 'Dağ', 'Şehir turu', 'Evde dinlenmek'] },
    { questionTR: 'Hafta sonu planın?', category: CardCategory.LIFESTYLE, options: ['Dışarıda', 'Evde', 'Spor', 'Arkadaşlarla'] },
    { questionTR: 'Güne başlama ritüelin?', category: CardCategory.LIFESTYLE, options: ['Kahve', 'Duş', 'Sosyal medya', 'Alarmı ertelerim'] },
    { questionTR: 'Uyku düzenin nasıl?', category: CardCategory.LIFESTYLE, options: ['Erken yatarım', 'Geç yatarım', 'Düzensiz', 'Değişken'] },
    { questionTR: 'Sporla aran nasıl?', category: CardCategory.LIFESTYLE, options: ['Düzenli yaparım', 'Ara sıra', 'Seyirciyim', 'Hiç sevmem'] },
    { questionTR: 'Alışveriş tarzın?', category: CardCategory.LIFESTYLE, options: ['Planlı', 'Spontane', 'İndirim beklerim', 'İhtiyaç oldukça'] },
    { questionTR: 'Yemek yapma becerin?', category: CardCategory.LIFESTYLE, options: ['Şef gibiyim', 'İdare eder', 'Menemen bile zor', 'Dışarıdan söylerim'] },
    { questionTR: 'Ev düzenin nasıldır?', category: CardCategory.LIFESTYLE, options: ['Tertemiz', 'Dağınık ama temiz', 'Kreatif kaos', 'Hiç sorma'] },
    { questionTR: 'Toplu taşımaya bakışın?', category: CardCategory.LIFESTYLE, options: ['Sık kullanırım', 'Mecbur kalınca', 'Mümkünse taksi', 'Arabasız asla'] },
    { questionTR: 'Kahve tercihlerin?', category: CardCategory.LIFESTYLE, options: ['Sade/Türk kahvesi', 'Latte/Cappuccino', 'Filtre kahve', 'Kahve içmem'] },
    { questionTR: 'Gece hayatı senin için?', category: CardCategory.LIFESTYLE, options: ['Vazgeçilmez', 'Ara sıra', 'Nadiren', 'Hiç sevmem'] },
    { questionTR: 'Çalışma stilin?', category: CardCategory.LIFESTYLE, options: ['Erken kalkan', 'Gece çalışan', 'Son dakikacı', 'Düzenli ve planlı'] },
    { questionTR: 'Tek başına vakit geçirme?', category: CardCategory.LIFESTYLE, options: ['Çok severim', 'Dengeli olmalı', 'Pek sevmem', 'Asla yalnız kalmam'] },
    { questionTR: 'Telefon kullanımın?', category: CardCategory.LIFESTYLE, options: ['Sürekli elimde', 'İş için daha çok', 'Sosyal medya ağırlıklı', 'Mecbur kalınca'] },
    { questionTR: 'Sabah uyanınca ilk ne yaparsın?', category: CardCategory.LIFESTYLE, options: ['Telefona bakarım', 'Duş alırım', 'Kahvaltı yaparım', 'Biraz daha uyurum'] },
    { questionTR: 'Akşam yemeği genelde saat kaçta?', category: CardCategory.LIFESTYLE, options: ['18-19 arası', '19-20 arası', '20-21 arası', 'Düzensiz'] },
    { questionTR: 'Fast food mu, ev yemeği mi?', category: CardCategory.LIFESTYLE, options: ['Fast food', 'Ev yemeği', 'Dengeli', 'Restoran'] },
    { questionTR: 'Spor salonu mu, açık hava mı?', category: CardCategory.LIFESTYLE, options: ['Spor salonu', 'Açık hava', 'Ev egzersizi', 'Spor yapmam'] },
    { questionTR: 'Araba mı, motorsiklet mi?', category: CardCategory.LIFESTYLE, options: ['Araba', 'Motorsiklet', 'Toplu taşıma', 'Bisiklet'] },
    { questionTR: 'Kış tatili mi, yaz tatili mi?', category: CardCategory.LIFESTYLE, options: ['Kış tatili', 'Yaz tatili', 'İkisi de', 'Tatil yapmam'] },
    { questionTR: 'Plaj mı, havuz mu?', category: CardCategory.LIFESTYLE, options: ['Plaj', 'Havuz', 'İkisi de', 'Hiçbiri'] },
    { questionTR: 'Kamp yapmayı sever misin?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Pek değil', 'Hiç sevmem'] },
    { questionTR: 'Doğa yürüyüşü?', category: CardCategory.LIFESTYLE, options: ['Sık yaparım', 'Ara sıra', 'Nadiren', 'Hiç yapmam'] },
    { questionTR: 'Yüzme bilir misin?', category: CardCategory.LIFESTYLE, options: ['Evet, çok iyi', 'İdare eder', 'Biraz', 'Hayır'] },
    { questionTR: 'Kayak/snowboard?', category: CardCategory.LIFESTYLE, options: ['Profesyonel', 'Amatör', 'Hiç denemedim', 'Denemek isterim'] },
    { questionTR: 'Dans eder misin?', category: CardCategory.LIFESTYLE, options: ['Çok severim', 'Ortam olunca', 'Pek değil', 'Asla'] },
    { questionTR: 'Enstrüman çalar mısın?', category: CardCategory.LIFESTYLE, options: ['Evet', 'Öğreniyorum', 'Bıraktım', 'Hayır'] },
    { questionTR: 'Resim çizer misin?', category: CardCategory.LIFESTYLE, options: ['Evet, hobi', 'Arada', 'Çöp adam bile zor', 'Hiç'] },
    { questionTR: 'Fotoğrafçılık?', category: CardCategory.LIFESTYLE, options: ['Profesyonel', 'Hobi', 'Sadece telefon', 'İlgim yok'] },
    { questionTR: 'Bahçecilik/bitki yetiştirme?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Birkaç saksım var', 'Hepsini öldürürüm', 'İlgim yok'] },
    { questionTR: 'Yoga/meditasyon?', category: CardCategory.LIFESTYLE, options: ['Düzenli yaparım', 'Ara sıra', 'Denedim bıraktım', 'Hiç denemedim'] },
    { questionTR: 'Koşu/jogging?', category: CardCategory.LIFESTYLE, options: ['Her gün', 'Haftada birkaç', 'Nadiren', 'Hiç'] },
    { questionTR: 'Bisiklet sürer misin?', category: CardCategory.LIFESTYLE, options: ['Ulaşım için', 'Spor olarak', 'Arada', 'Hiç'] },
    { questionTR: 'Dövüş sporları?', category: CardCategory.LIFESTYLE, options: ['Aktif yaparım', 'Eskiden yapardım', 'İlgilenirim', 'Hiç'] },
    { questionTR: 'Tenis/badminton?', category: CardCategory.LIFESTYLE, options: ['Düzenli', 'Ara sıra', 'Nadiren', 'Hiç'] },
    { questionTR: 'Futbol/basketbol?', category: CardCategory.LIFESTYLE, options: ['Oynarım', 'Seyrederim', 'İkisi de', 'İlgim yok'] },
    { questionTR: 'E-spor/gaming?', category: CardCategory.LIFESTYLE, options: ['Ciddi oynarım', 'Casual', 'Ara sıra', 'Hiç'] },
    { questionTR: 'Konsol mu, PC mi?', category: CardCategory.LIFESTYLE, options: ['Konsol', 'PC', 'İkisi de', 'Hiçbiri'] },
    { questionTR: 'Netflix bir gecede kaç bölüm?', category: CardCategory.LIFESTYLE, options: ['1-2', '3-4', '5+', 'Dizi izlemem'] },
    { questionTR: 'Sinema mı, evde film mi?', category: CardCategory.LIFESTYLE, options: ['Sinema', 'Evde', 'İkisi de', 'Film izlemem'] },
    { questionTR: 'Tiyatroya gider misin?', category: CardCategory.LIFESTYLE, options: ['Sık sık', 'Ara sıra', 'Nadiren', 'Hiç'] },
    { questionTR: 'Konsere gider misin?', category: CardCategory.LIFESTYLE, options: ['Çok sık', 'Yılda birkaç', 'Nadiren', 'Hiç'] },
    { questionTR: 'Müze/sergi?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Nadiren', 'Sıkıcı buluyorum'] },
    { questionTR: 'Opera/bale?', category: CardCategory.LIFESTYLE, options: ['Severim', 'Merak ederim', 'Pek değil', 'Hiç'] },
    { questionTR: 'Stand-up gösterisi?', category: CardCategory.LIFESTYLE, options: ['Çok severim', 'Ara sıra', 'Pek değil', 'Hiç gitmedim'] },
    { questionTR: 'Karaoke?', category: CardCategory.LIFESTYLE, options: ['Her zaman', 'İçince', 'Asla', 'Dinlerim sadece'] },
    { questionTR: 'Parti mi, buluşma mı?', category: CardCategory.LIFESTYLE, options: ['Büyük parti', 'Küçük buluşma', 'İkisi de', 'Evde kalmak'] },
    { questionTR: 'Bar mı, kafe mi?', category: CardCategory.LIFESTYLE, options: ['Bar', 'Kafe', 'İkisi de', 'Evde'] },
    { questionTR: 'Gece kulübü?', category: CardCategory.LIFESTYLE, options: ['Haftada bir', 'Ayda bir', 'Nadiren', 'Asla'] },
    { questionTR: 'Piknik yapar mısın?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Pek değil', 'Hiç'] },
    { questionTR: 'Mangal/BBQ?', category: CardCategory.LIFESTYLE, options: ['Uzmanım', 'Severim', 'Yerim sadece', 'Vejetaryenim'] },
    { questionTR: 'Balık tutmak?', category: CardCategory.LIFESTYLE, options: ['Hobi', 'Denedim', 'İlgim yok', 'Sıkıcı'] },
    { questionTR: 'Dalış/şnorkel?', category: CardCategory.LIFESTYLE, options: ['Lisanslıyım', 'Denedim', 'Denemek isterim', 'Korkutucu'] },
    { questionTR: 'Paraşüt/bungee jumping?', category: CardCategory.LIFESTYLE, options: ['Yaptım', 'Yapmak isterim', 'Belki', 'Asla'] },
    { questionTR: 'Tırmanış?', category: CardCategory.LIFESTYLE, options: ['Hobi', 'Denedim', 'İlgim var', 'Yükseklik korkum var'] },
    { questionTR: 'At binme?', category: CardCategory.LIFESTYLE, options: ['Düzenli', 'Birkaç kez', 'Hiç', 'Denemek isterim'] },
    { questionTR: 'Seyahat sıklığın?', category: CardCategory.LIFESTYLE, options: ['Ayda bir', 'Yılda birkaç', 'Yılda bir', 'Nadiren'] },
    { questionTR: 'Yurt dışı seyahati?', category: CardCategory.LIFESTYLE, options: ['Çok gittim', 'Birkaç kez', 'Hiç gitmedim', 'Planlarım var'] },
    { questionTR: 'Solo seyahat?', category: CardCategory.LIFESTYLE, options: ['Tercih ederim', 'Yaptım', 'Denemek isterim', 'Asla'] },
    { questionTR: 'Hostel mi, otel mi?', category: CardCategory.LIFESTYLE, options: ['Hostel', 'Otel', 'Airbnb', 'Fark etmez'] },
    { questionTR: 'Uçak korkun var mı?', category: CardCategory.LIFESTYLE, options: ['Hayır', 'Biraz', 'Evet', 'Uçmadım'] },
    { questionTR: 'Road trip?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Pek değil', 'Hiç yapmadım'] },
    { questionTR: 'Tren yolculuğu?', category: CardCategory.LIFESTYLE, options: ['Romantik buluyorum', 'Pratik', 'Sıkıcı', 'Hiç yapmadım'] },
    { questionTR: 'Cruise/gemi tatili?', category: CardCategory.LIFESTYLE, options: ['Yaptım', 'Yapmak isterim', 'Pek değil', 'Deniz tutması'] },
    { questionTR: 'Safari?', category: CardCategory.LIFESTYLE, options: ['Hayalim', 'Yaptım', 'İlgim yok', 'Korkutucu'] },
    { questionTR: 'Antik şehir gezisi?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'İlginç', 'Sıkıcı', 'Hiç gitmedim'] },
    { questionTR: 'Tema parkı?', category: CardCategory.LIFESTYLE, options: ['Çok severim', 'Ara sıra', 'Çocuklar için', 'Hiç'] },
    { questionTR: 'Lunapark?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Nostalji', 'Pek değil', 'Korkarım'] },
    { questionTR: 'Akvaryum/hayvanat bahçesi?', category: CardCategory.LIFESTYLE, options: ['Severim', 'Ara sıra', 'Etik bulmam', 'İlgim yok'] },
    { questionTR: 'Botanik bahçe?', category: CardCategory.LIFESTYLE, options: ['Huzur veriyor', 'Güzel', 'Sıkıcı', 'Hiç gitmedim'] },
    { questionTR: 'Alışveriş merkezi?', category: CardCategory.LIFESTYLE, options: ['Sık giderim', 'İhtiyaç olunca', 'Online tercih', 'Sevmem'] },
    { questionTR: 'Pazar/bit pazarı?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Pek değil', 'Hiç'] },
    { questionTR: 'Antika/koleksiyon?', category: CardCategory.LIFESTYLE, options: ['Koleksiyonerim', 'İlgili', 'Biraz', 'Hiç'] },
    { questionTR: 'El işi/DIY?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Ara sıra', 'Pek beceremem', 'Hiç'] },
    { questionTR: 'Dikişin/örgü?', category: CardCategory.LIFESTYLE, options: ['Yaparım', 'Öğreniyorum', 'Bilmiyorum', 'İlgim yok'] },
    { questionTR: 'Marangozluk?', category: CardCategory.LIFESTYLE, options: ['Hobi', 'Basit işler', 'Hiç', 'Öğrenmek isterim'] },
    { questionTR: 'Araba tamiri?', category: CardCategory.LIFESTYLE, options: ['Yapabilirim', 'Basit şeyler', 'Hiç', 'Servise götürürüm'] },
    { questionTR: 'Teknoloji ürünlerini kendin tamir eder misin?', category: CardCategory.LIFESTYLE, options: ['Evet', 'Denerdim', 'YouTube izlerim', 'Asla'] },
    { questionTR: 'Geri dönüşüm yapar mısın?', category: CardCategory.LIFESTYLE, options: ['Kesinlikle', 'Çoğunlukla', 'Bazen', 'Hayır'] },
    { questionTR: 'Vejetaryen/vegan misin?', category: CardCategory.LIFESTYLE, options: ['Vegan', 'Vejetaryen', 'Flexitarian', 'Hayır'] },
    { questionTR: 'Organik ürün tercihi?', category: CardCategory.LIFESTYLE, options: ['Her zaman', 'Mümkünse', 'Bazen', 'Fark etmez'] },
    { questionTR: 'Diyet yapar mısın?', category: CardCategory.LIFESTYLE, options: ['Sürekli', 'Ara sıra', 'Denedim bıraktım', 'Hiç'] },
    { questionTR: 'Vitamin/takviye kullanır mısın?', category: CardCategory.LIFESTYLE, options: ['Düzenli', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Doktora gitme sıklığın?', category: CardCategory.LIFESTYLE, options: ['Düzenli check-up', 'Gerekince', 'Mecbur kalınca', 'Kaçınırım'] },
    { questionTR: 'Alternatif tıp?', category: CardCategory.LIFESTYLE, options: ['İnanırım', 'Açık fikirliyim', 'Şüpheciyim', 'Saçmalık'] },
    { questionTR: 'Sigara içer misin?', category: CardCategory.LIFESTYLE, options: ['Evet', 'Sosyal içici', 'Bıraktım', 'Hayır'] },
    { questionTR: 'Alkol alır mısın?', category: CardCategory.LIFESTYLE, options: ['Düzenli', 'Sosyal', 'Nadiren', 'Hiç'] },
    { questionTR: 'Favori içeceğin?', category: CardCategory.LIFESTYLE, options: ['Bira', 'Şarap', 'Kokteyl', 'Rakı'] },
    { questionTR: 'Kahve mi, çay mı?', category: CardCategory.LIFESTYLE, options: ['Kahve', 'Çay', 'İkisi de', 'Hiçbiri'] },
    { questionTR: 'Enerji içeceği?', category: CardCategory.LIFESTYLE, options: ['Sık içerim', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Su içme alışkanlığın?', category: CardCategory.LIFESTYLE, options: ['2L+ günde', 'Yeterli', 'Az içerim', 'Hatırlamam'] },
    { questionTR: 'Yeme alışkanlığın?', category: CardCategory.LIFESTYLE, options: ['3 öğün düzenli', '2 öğün', 'Düzensiz', 'Sürekli atıştırma'] },
    { questionTR: 'Gece atıştırmalığı?', category: CardCategory.LIFESTYLE, options: ['Her zaman', 'Bazen', 'Nadiren', 'Asla'] },
    { questionTR: 'Tatlı mı, tuzlu mu?', category: CardCategory.LIFESTYLE, options: ['Tatlı', 'Tuzlu', 'İkisi de', 'Fark etmez'] },
    { questionTR: 'Acı sever misin?', category: CardCategory.LIFESTYLE, options: ['Çok acı', 'Orta acı', 'Az acı', 'Hiç'] },
    { questionTR: 'Deniz ürünleri?', category: CardCategory.LIFESTYLE, options: ['Bayılırım', 'Severim', 'Pek değil', 'Alerjim var/Sevmem'] },
    { questionTR: 'Sushi?', category: CardCategory.LIFESTYLE, options: ['Favori', 'Severim', 'Denedim', 'Çiğ yenmez'] },
    { questionTR: 'Pizza topping tercihin?', category: CardCategory.LIFESTYLE, options: ['Et/sucuk', 'Karışık', 'Vejetaryen', 'Margarita'] },
    
    // ==================== VALUES (200) ====================
    { questionTR: 'İlişkide en önemli?', category: CardCategory.VALUES, options: ['Güven', 'Sadakat', 'İletişim', 'Heyecan'] },
    { questionTR: 'Kendi mutluluğun mu önemli?', category: CardCategory.VALUES, options: ['Tabii ki', 'Başkalarının da önemli', 'Dengeli olmalı', 'Başkaları önce'] },
    { questionTR: 'Para senin için?', category: CardCategory.VALUES, options: ['Güvenlik', 'Özgürlük', 'Araç', 'Önemli değil'] },
    { questionTR: 'Aile ile ilişkiler?', category: CardCategory.VALUES, options: ['Çok yakınım', 'Dengeli', 'Mesafeli', 'Karmaşık'] },
    { questionTR: 'Kariyer mi, aşk mı?', category: CardCategory.VALUES, options: ['Kariyer', 'Aşk', 'Denge', 'Döneme göre'] },
    { questionTR: 'Evlilik hakkında?', category: CardCategory.VALUES, options: ['Kesin isterim', 'Olursa olur', 'Kararsızım', 'İstemiyorum'] },
    { questionTR: 'Çocuk sahibi olmak?', category: CardCategory.VALUES, options: ['Kesin isterim', 'Belki ileride', 'Kararsızım', 'İstemiyorum'] },
    { questionTR: 'Dürüstlük anlayışın?', category: CardCategory.VALUES, options: ['Her zaman tam', 'Beyaz yalan olabilir', 'Duruma göre', 'Gizlemek daha iyi'] },
    { questionTR: 'Fedakarlık sınırın?', category: CardCategory.VALUES, options: ['Kendimden vazgeçerim', 'Dengeli olmalı', 'Sınırlarım net', 'Minimum'] },
    { questionTR: 'İlişkide kıskançlık?', category: CardCategory.VALUES, options: ['Olmalı, dozunda', 'Hiç sevmem', 'Biraz tatlıdır', 'Beni boğar'] },
    { questionTR: 'Bağımsızlık senin için?', category: CardCategory.VALUES, options: ['Olmazsa olmaz', 'İlişkide paylaşılır', 'Çok önemli değil', 'Partner odaklıyım'] },
    { questionTR: 'Gelecek planların?', category: CardCategory.VALUES, options: ['Net planlarım var', 'Taslak var', 'Akışa bırakıyorum', 'Düşünmedim'] },
    { questionTR: 'Sadakat tanımın?', category: CardCategory.VALUES, options: ['Söz, davranış, düşünce', 'Davranış önemli', 'Sınırlar konuşulur', 'Göreceli'] },
    { questionTR: 'İlişkide roller?', category: CardCategory.VALUES, options: ['Geleneksel', 'Eşitlikçi', 'Duruma göre', 'Düşünmedim'] },
    { questionTR: 'Kriz anında tavrın?', category: CardCategory.VALUES, options: ['Sakin kalırım', 'Duygusal tepki', 'İçe kapanırım', 'Kaçmayı tercih'] },
    { questionTR: 'Affetme kapasiten?', category: CardCategory.VALUES, options: ['Kolay affederim', 'Zaman alır', 'Zor affederim', 'Unutmam'] },
    { questionTR: 'Özür dilemek?', category: CardCategory.VALUES, options: ['Kolay', 'Haklıysam', 'Zor', 'Nadiren'] },
    { questionTR: 'İlk adımı kim atmalı?', category: CardCategory.VALUES, options: ['Ben atarım', 'Karşı taraf', 'Fark etmez', 'Duruma göre'] },
    { questionTR: 'Flört sürecinde kim ödemeli?', category: CardCategory.VALUES, options: ['Erkek', 'Ortadan', 'Davet eden', 'Sırayla'] },
    { questionTR: 'Uzun mesafe ilişki?', category: CardCategory.VALUES, options: ['Yapabilirim', 'Zor ama denerdim', 'Pek değil', 'Asla'] },
    { questionTR: 'Eski sevgiliyle arkadaş?', category: CardCategory.VALUES, options: ['Olabilir', 'Duruma göre', 'Zor', 'Asla'] },
    { questionTR: 'Partner seçiminde yaş?', category: CardCategory.VALUES, options: ['Fark etmez', 'Yakın olmalı', 'Büyük olabilir', 'Küçük olabilir'] },
    { questionTR: 'Boy farkı önemli mi?', category: CardCategory.VALUES, options: ['Evet, çok', 'Biraz', 'Pek değil', 'Hiç'] },
    { questionTR: 'Fiziksel çekim mi, karakter mi?', category: CardCategory.VALUES, options: ['Fiziksel', 'Karakter', 'İkisi de eşit', 'Önce fiziksel sonra karakter'] },
    { questionTR: 'Partnerinle her şeyi paylaşır mısın?', category: CardCategory.VALUES, options: ['Evet, her şeyi', 'Çoğu şeyi', 'Bazı şeyleri', 'Kendi alanım olmalı'] },
    { questionTR: 'Telefon şifreni paylaşır mısın?', category: CardCategory.VALUES, options: ['Evet', 'İsterse', 'Hayır', 'Karşılıklı olursa'] },
    { questionTR: 'Sosyal medyada ilişki durumu?', category: CardCategory.VALUES, options: ['Paylaşırım', 'Gerek yok', 'Özel kalmalı', 'İkimiz bilsek yeter'] },
    { questionTR: 'Birlikte yaşamak?', category: CardCategory.VALUES, options: ['Evlenmeden olmaz', 'Deneme şart', 'Nişandan sonra', 'Hemen olabilir'] },
    { questionTR: 'Ev işleri paylaşımı?', category: CardCategory.VALUES, options: ['Eşit', 'Duruma göre', 'Birine göre', 'Yardımcı tutarız'] },
    { questionTR: 'Maddi konular nasıl yönetilmeli?', category: CardCategory.VALUES, options: ['Ortak hesap', 'Ayrı hesaplar', 'Karma sistem', 'Duruma göre'] },
    { questionTR: 'Tatil planlaması?', category: CardCategory.VALUES, options: ['Birlikte karar', 'Sürpriz sevmem', 'O planlasın', 'Ben planlarım'] },
    { questionTR: 'Arkadaşlarla vakit?', category: CardCategory.VALUES, options: ['Birlikte olmalı', 'Ayrı olabilir', 'Dengeli', 'Kendi arkadaşlarım'] },
    { questionTR: 'Aile ziyaretleri sıklığı?', category: CardCategory.VALUES, options: ['Çok sık', 'Haftalık', 'Aylık', 'Bayramlarda'] },
    { questionTR: 'Evcil hayvan?', category: CardCategory.VALUES, options: ['Olmazsa olmaz', 'Olabilir', 'Pek istemem', 'Kesinlikle hayır'] },
    { questionTR: 'Çocuk yetiştirme tarzı?', category: CardCategory.VALUES, options: ['Serbest', 'Dengeli', 'Disiplinli', 'Düşünmedim'] },
    { questionTR: 'Din/inanç konusu?', category: CardCategory.VALUES, options: ['Çok önemli', 'Orta derecede', 'Pek değil', 'Hiç önemli değil'] },
    { questionTR: 'Politik görüş uyumu?', category: CardCategory.VALUES, options: ['Şart', 'Tercih', 'Fark etmez', 'Konuşulmaz'] },
    { questionTR: 'Çevre/doğa hassasiyeti?', category: CardCategory.VALUES, options: ['Çok önemli', 'Önemli', 'Biraz', 'Değil'] },
    { questionTR: 'Hayvan hakları?', category: CardCategory.VALUES, options: ['Aktivistim', 'Önemserim', 'Biraz', 'Abartılıyor'] },
    { questionTR: 'Sosyal sorumluluk?', category: CardCategory.VALUES, options: ['Aktif katılırım', 'Desteklerim', 'Ara sıra', 'İlgim yok'] },
    { questionTR: 'Bağış/yardım?', category: CardCategory.VALUES, options: ['Düzenli yaparım', 'Fırsat buldukça', 'Nadiren', 'Yapmam'] },
    { questionTR: 'Başarı senin için?', category: CardCategory.VALUES, options: ['Kariyer', 'Mutlu aile', 'İç huzur', 'Para'] },
    { questionTR: 'Hayatın anlamı?', category: CardCategory.VALUES, options: ['Deneyimler', 'İlişkiler', 'Başarı', 'Eğlence'] },
    { questionTR: 'Mutluluk kaynağın?', category: CardCategory.VALUES, options: ['Sevdiklerim', 'Başarılarım', 'Hobiler', 'İç huzur'] },
    { questionTR: 'Stres kaynağın?', category: CardCategory.VALUES, options: ['İş', 'İlişkiler', 'Para', 'Belirsizlik'] },
    { questionTR: 'En büyük korkun?', category: CardCategory.VALUES, options: ['Yalnızlık', 'Başarısızlık', 'Kayıp', 'Hastalık'] },
    { questionTR: 'Pişmanlık hisseder misin?', category: CardCategory.VALUES, options: ['Çok', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Geçmişe mi, geleceğe mi bakarsın?', category: CardCategory.VALUES, options: ['Geçmiş', 'Gelecek', 'Şu an', 'Dengeli'] },
    { questionTR: 'Şans mı, emek mi?', category: CardCategory.VALUES, options: ['Şans', 'Emek', 'İkisi de', 'Kader'] },
    { questionTR: 'Kaderci misin?', category: CardCategory.VALUES, options: ['Evet', 'Biraz', 'Hayır', 'Bilmiyorum'] },
    { questionTR: 'Batıl inanç?', category: CardCategory.VALUES, options: ['İnanırım', 'Bazılarına', 'Saçmalık', 'Eğlenceli'] },
    { questionTR: 'Burçlara inanır mısın?', category: CardCategory.VALUES, options: ['Evet', 'Eğlence olarak', 'Pek değil', 'Hiç'] },
    { questionTR: 'Rüyalara anlam yükler misin?', category: CardCategory.VALUES, options: ['Evet', 'Bazen', 'Hayır', 'Rüya görmem'] },
    { questionTR: 'İlişkide denge mi, tutku mu?', category: CardCategory.VALUES, options: ['Denge', 'Tutku', 'İkisi de', 'Zamanla değişir'] },
    { questionTR: 'Aşk acı çeker mi?', category: CardCategory.VALUES, options: ['Evet', 'Bazen', 'Olmamalı', 'Hayır'] },
    { questionTR: 'Tek eş mi, açık ilişki mi?', category: CardCategory.VALUES, options: ['Kesinlikle tek eş', 'Tek eş tercih', 'Açık olabilir', 'Fark etmez'] },
    
    // ==================== INTERESTS (200) ====================
    { questionTR: 'Film türü?', category: CardCategory.INTERESTS, options: ['Komedi', 'Aksiyon', 'Romantik', 'Korku'] },
    { questionTR: 'Müzik tarzın?', category: CardCategory.INTERESTS, options: ['Pop', 'Rock', 'Rap', 'Klasik'] },
    { questionTR: 'Kitap tercihlerin?', category: CardCategory.INTERESTS, options: ['Kurgu', 'Kişisel gelişim', 'Tarih', 'Pek okumam'] },
    { questionTR: 'Oyunlarla aran?', category: CardCategory.INTERESTS, options: ['PC/Console', 'Masa oyunları', 'Mobil', 'Oynamam'] },
    { questionTR: 'Seyahat tarzın?', category: CardCategory.INTERESTS, options: ['Backpacker', 'Konforlu otel', 'Aile yanında', 'Evde kalırım'] },
    { questionTR: 'Sanatla ilişkin?', category: CardCategory.INTERESTS, options: ['Aktif ilgilenirim', 'Takip ederim', 'Ara sıra', 'Pek yok'] },
    { questionTR: 'Dizi izleme alışkanlığın?', category: CardCategory.INTERESTS, options: ['Binge-watcher', 'Haftalık takip', 'Nadiren', 'Hiç'] },
    { questionTR: 'Sosyal medya kullanımın?', category: CardCategory.INTERESTS, options: ['Çok aktif', 'Orta düzey', 'Az', 'Kullanmam'] },
    { questionTR: 'En çok keyif aldığın aktivite?', category: CardCategory.INTERESTS, options: ['Sosyalleşmek', 'Film/dizi', 'Doğa yürüyüşü', 'Yaratıcı hobiler'] },
    { questionTR: 'Takım sporlarıyla aran?', category: CardCategory.INTERESTS, options: ['Oynamayı severim', 'Seyretmeyi severim', 'Ara sıra', 'İlgi duymam'] },
    { questionTR: 'Podcast dinler misin?', category: CardCategory.INTERESTS, options: ['Sık sık', 'Ara sıra', 'Nadiren', 'Hiç'] },
    { questionTR: 'Teknolojiye bakışın?', category: CardCategory.INTERESTS, options: ['Erken benimseyen', 'Takip ederim', 'Gerektiği kadar', 'Mecbur kalınca'] },
    { questionTR: 'Evcil hayvanlarla aran?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Severim ama bakamam', 'Mesafeliyim', 'Sevmem'] },
    { questionTR: 'Hafta içi akşamları?', category: CardCategory.INTERESTS, options: ['Dışarıda', 'Evde dinlenme', 'Ek iş/üretim', 'Aile/arkadaş'] },
    { questionTR: 'Hafta sonu kaçamak?', category: CardCategory.INTERESTS, options: ['Yakın şehir', 'Doğa kaçamağı', 'Evde kalmak', 'Arkadaşlarla plan'] },
    { questionTR: 'Favori film serisi?', category: CardCategory.INTERESTS, options: ['Marvel', 'DC', 'Star Wars', 'Lord of the Rings'] },
    { questionTR: 'Türk dizisi izler misin?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Bazıları güzel', 'Pek değil', 'Hiç'] },
    { questionTR: 'Anime izler misin?', category: CardCategory.INTERESTS, options: ['Otaku', 'Severim', 'Birkaç izledim', 'Hiç'] },
    { questionTR: 'Belgesel?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Konuya göre', 'Nadiren', 'Sıkıcı'] },
    { questionTR: 'Reality show?', category: CardCategory.INTERESTS, options: ['Bağımlısıyım', 'Bazen', 'Saçma buluyorum', 'Hiç'] },
    { questionTR: 'Yarışma programları?', category: CardCategory.INTERESTS, options: ['Severim', 'Bazıları', 'Pek değil', 'Hiç'] },
    { questionTR: 'Haber takibi?', category: CardCategory.INTERESTS, options: ['Sürekli', 'Günlük', 'Ara sıra', 'Hiç'] },
    { questionTR: 'YouTube kullanımı?', category: CardCategory.INTERESTS, options: ['Her gün', 'Sık sık', 'Bazen', 'Nadiren'] },
    { questionTR: 'TikTok?', category: CardCategory.INTERESTS, options: ['Bağımlıyım', 'Kullanırım', 'Pek değil', 'Yok'] },
    { questionTR: 'Instagram?', category: CardCategory.INTERESTS, options: ['Çok aktif', 'Aktif', 'Pasif', 'Yok'] },
    { questionTR: 'Twitter/X?', category: CardCategory.INTERESTS, options: ['Her gün', 'Takip ederim', 'Nadiren', 'Yok'] },
    { questionTR: 'LinkedIn?', category: CardCategory.INTERESTS, options: ['Aktif', 'Var ama pasif', 'Sadece iş için', 'Yok'] },
    { questionTR: 'Twitch/yayın?', category: CardCategory.INTERESTS, options: ['Yayıncıyım', 'İzlerim', 'Bazen', 'Hiç'] },
    { questionTR: 'Müzik dinleme platformu?', category: CardCategory.INTERESTS, options: ['Spotify', 'Apple Music', 'YouTube Music', 'Diğer'] },
    { questionTR: 'Canlı müzik mi, stüdyo kaydı mı?', category: CardCategory.INTERESTS, options: ['Canlı', 'Stüdyo', 'İkisi de', 'Fark etmez'] },
    { questionTR: 'Festival?', category: CardCategory.INTERESTS, options: ['Her yıl giderim', 'Ara sıra', 'Bir kez gittim', 'Hiç gitmedim'] },
    { questionTR: 'Türk müziği?', category: CardCategory.INTERESTS, options: ['Sadece Türk', 'Karışık', 'Yabancı ağırlıklı', 'Dinlemem'] },
    { questionTR: 'Klasik müzik?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Hoş', 'Pek değil', 'Hiç'] },
    { questionTR: 'Jazz?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Güzel', 'Bazen', 'Anlamam'] },
    { questionTR: 'Elektronik müzik?', category: CardCategory.INTERESTS, options: ['Favorim', 'Severim', 'Bazen', 'Gürültü'] },
    { questionTR: 'Metal/Rock?', category: CardCategory.INTERESTS, options: ['Hayat tarzım', 'Severim', 'Bazen', 'Çok gürültülü'] },
    { questionTR: 'Pop müzik?', category: CardCategory.INTERESTS, options: ['Her zaman', 'Güzel', 'Bazen', 'Kalitesiz'] },
    { questionTR: 'Rap/Hip-hop?', category: CardCategory.INTERESTS, options: ['Favorim', 'Severim', 'Bazıları', 'Hiç'] },
    { questionTR: 'Arabesk?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Nostalji', 'Bazen', 'Hiç'] },
    { questionTR: 'Kitap mı, e-kitap mı?', category: CardCategory.INTERESTS, options: ['Fiziksel kitap', 'E-kitap', 'İkisi de', 'Fark etmez'] },
    { questionTR: 'Ayda kaç kitap okursun?', category: CardCategory.INTERESTS, options: ['3+', '1-2', 'Yılda birkaç', 'Hiç'] },
    { questionTR: 'Favori yazar türü?', category: CardCategory.INTERESTS, options: ['Yerli', 'Yabancı', 'Karışık', 'Okumam'] },
    { questionTR: 'Dergi/gazete?', category: CardCategory.INTERESTS, options: ['Düzenli', 'Dijital', 'Nadiren', 'Hiç'] },
    { questionTR: 'Çizgi roman/manga?', category: CardCategory.INTERESTS, options: ['Koleksiyoner', 'Severim', 'Birkaç', 'Hiç'] },
    { questionTR: 'Bilim kurgu?', category: CardCategory.INTERESTS, options: ['En sevdiğim', 'Severim', 'Bazen', 'Pek değil'] },
    { questionTR: 'Fantastik?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Güzel', 'Bazen', 'Pek değil'] },
    { questionTR: 'Polisiye/gerilim?', category: CardCategory.INTERESTS, options: ['Favorim', 'Severim', 'Bazen', 'Pek değil'] },
    { questionTR: 'Romantik hikayeler?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Güzel', 'Bazen', 'Sıkıcı'] },
    { questionTR: 'Tarih?', category: CardCategory.INTERESTS, options: ['Çok ilgiliyim', 'İlginç', 'Biraz', 'İlgim yok'] },
    { questionTR: 'Felsefe?', category: CardCategory.INTERESTS, options: ['Derinlemesine', 'İlginç', 'Zor', 'İlgim yok'] },
    { questionTR: 'Psikoloji?', category: CardCategory.INTERESTS, options: ['Çok ilgiliyim', 'Merak ederim', 'Biraz', 'Pek değil'] },
    { questionTR: 'Ekonomi/finans?', category: CardCategory.INTERESTS, options: ['Takip ederim', 'İlgiliyim', 'Gerektiğince', 'Hiç'] },
    { questionTR: 'Yatırım?', category: CardCategory.INTERESTS, options: ['Aktif yatırımcı', 'Biraz', 'Öğreniyorum', 'İlgim yok'] },
    { questionTR: 'Kripto?', category: CardCategory.INTERESTS, options: ['Trader', 'Biraz var', 'Merak ediyorum', 'Uzak duruyorum'] },
    { questionTR: 'Borsayı takip eder misin?', category: CardCategory.INTERESTS, options: ['Her gün', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Girişimcilik?', category: CardCategory.INTERESTS, options: ['Girişimciyim', 'Hayalim', 'İlginç', 'Pek değil'] },
    { questionTR: 'Yan iş/freelance?', category: CardCategory.INTERESTS, options: ['Yapıyorum', 'Düşünüyorum', 'Denedim', 'Hayır'] },
    { questionTR: 'Kodlama/programlama?', category: CardCategory.INTERESTS, options: ['Profesyonel', 'Hobi', 'Öğreniyorum', 'Hiç'] },
    { questionTR: 'Yapay zeka?', category: CardCategory.INTERESTS, options: ['Çok ilgiliyim', 'Takip ediyorum', 'Biraz', 'Korkutucu'] },
    { questionTR: 'Uzay/astronomi?', category: CardCategory.INTERESTS, options: ['Tutkum', 'İlginç', 'Bazen', 'Pek değil'] },
    { questionTR: 'Bilim haberleri?', category: CardCategory.INTERESTS, options: ['Takip ederim', 'İlginç', 'Bazen', 'Hiç'] },
    { questionTR: 'Doğa belgeselleri?', category: CardCategory.INTERESTS, options: ['Bayılırım', 'Güzel', 'Bazen', 'Sıkıcı'] },
    { questionTR: 'Hayvan belgeselleri?', category: CardCategory.INTERESTS, options: ['Favorim', 'Severim', 'Bazen', 'Üzücü'] },
    { questionTR: 'Suç belgeselleri?', category: CardCategory.INTERESTS, options: ['Bağımlısıyım', 'İlginç', 'Bazen', 'Rahatsız edici'] },
    
    // ==================== PERSONALITY (200) ====================
    { questionTR: 'Kendini nasıl tanımlarsın?', category: CardCategory.PERSONALITY, options: ['İçe dönük', 'Dışa dönük', 'Ortada', 'Duruma göre'] },
    { questionTR: 'Karar verme stilin?', category: CardCategory.PERSONALITY, options: ['Hızlı karar', 'Uzun düşünürüm', 'İçgüdülerim', 'Başkalarına sorarım'] },
    { questionTR: 'Stresle başa çıkma?', category: CardCategory.PERSONALITY, options: ['Spor', 'Yalnız kalmak', 'Arkadaşlarla', 'Ertelemek'] },
    { questionTR: 'Planlı mısın, spontan mı?', category: CardCategory.PERSONALITY, options: ['Çok planlı', 'Genelde planlı', 'Spontan', 'Akışına bırakırım'] },
    { questionTR: 'İlk tanışmada nasılsın?', category: CardCategory.PERSONALITY, options: ['Çok sosyal', 'Biraz çekingen', 'Sonra açılırım', 'Duruma göre'] },
    { questionTR: 'Tartışma anında?', category: CardCategory.PERSONALITY, options: ['Hemen konuşmak', 'Sakinleşip sonra', 'İçe kapanırım', 'Konuyu kapatırım'] },
    { questionTR: 'Romantiklik seviyen?', category: CardCategory.PERSONALITY, options: ['Aşırı romantik', 'Dengeli', 'Nadiren', 'Hiç değilim'] },
    { questionTR: 'Risk almaya bakışın?', category: CardCategory.PERSONALITY, options: ['Risk olmadan olmaz', 'Hesaplı risk', 'Güvenli bölge', 'Riskten kaçarım'] },
    { questionTR: 'Sabır seviyen?', category: CardCategory.PERSONALITY, options: ['Çok sabırlıyım', 'Genelde sabırlı', 'Çabuk sıkılırım', 'Hiç sabrım yok'] },
    { questionTR: 'Empati yeteneğin?', category: CardCategory.PERSONALITY, options: ['Çok yüksek', 'Dengeli', 'Duruma göre', 'Zorlanırım'] },
    { questionTR: 'Liderlik mi, takipçilik mi?', category: CardCategory.PERSONALITY, options: ['Lider', 'Duruma göre lider', 'Takımda olmak', 'Takipçi'] },
    { questionTR: 'Detaycı mısın?', category: CardCategory.PERSONALITY, options: ['Çok detaycı', 'Önemli konularda', 'Genel bakış', 'Hiç'] },
    { questionTR: 'Mükemmeliyetçi misin?', category: CardCategory.PERSONALITY, options: ['Aşırı', 'Biraz', 'Dengeli', 'Hiç'] },
    { questionTR: 'Rekabetçi misin?', category: CardCategory.PERSONALITY, options: ['Çok', 'Biraz', 'Sadece bazı konularda', 'Hiç'] },
    { questionTR: 'Eleştiriye tepkin?', category: CardCategory.PERSONALITY, options: ['Yapıcı bulurum', 'Zorlanırım', 'Alıngan olurum', 'Umursamam'] },
    { questionTR: 'Övgüye tepkin?', category: CardCategory.PERSONALITY, options: ['Mutlu olurum', 'Utanırım', 'Şüphelenirim', 'Normal karşılarım'] },
    { questionTR: 'Başarısızlık karşısında?', category: CardCategory.PERSONALITY, options: ['Tekrar denerim', 'Üzülür sonra devam', 'Zor toparlanırım', 'Bırakırım'] },
    { questionTR: 'Beklenmedik değişikliklere?', category: CardCategory.PERSONALITY, options: ['Hemen adapte', 'Biraz zaman alır', 'Zorlanırım', 'Çok stres'] },
    { questionTR: 'Sürprizlere tepkin?', category: CardCategory.PERSONALITY, options: ['Bayılırım', 'Güzel olabilir', 'Pek sevmem', 'Nefret ederim'] },
    { questionTR: 'Rutine bağlılığın?', category: CardCategory.PERSONALITY, options: ['Çok bağımlı', 'Seviyorum', 'Esnek', 'Rutinden nefret'] },
    { questionTR: 'Sosyal ortamlarda enerji?', category: CardCategory.PERSONALITY, options: ['Enerji alırım', 'Dengeli', 'Yorulurum', 'Kaçınırım'] },
    { questionTR: 'Yalnızken ne hissedersin?', category: CardCategory.PERSONALITY, options: ['Huzur', 'Normal', 'Sıkılırım', 'Mutsuz'] },
    { questionTR: 'Çatışma çözme tarzın?', category: CardCategory.PERSONALITY, options: ['Uzlaşmacı', 'Direkt konuşurum', 'Kaçınırım', 'Agresif'] },
    { questionTR: 'Güven inşası?', category: CardCategory.PERSONALITY, options: ['Yavaş yavaş', 'Hızlı güvenirim', 'Zor güvenirim', 'Kanıtlanmalı'] },
    { questionTR: 'İlk izlenim?', category: CardCategory.PERSONALITY, options: ['Çok önemli', 'Önemli', 'Değişebilir', 'Önemli değil'] },
    { questionTR: 'Öfke kontrolün?', category: CardCategory.PERSONALITY, options: ['Çok iyi', 'Genelde iyi', 'Zorlanırım', 'Patlayıcı'] },
    { questionTR: 'Endişe seviyen?', category: CardCategory.PERSONALITY, options: ['Çok endişeli', 'Normal', 'Sakin', 'Hiç endişelenmem'] },
    { questionTR: 'Karamsarlık mı, iyimserlik mi?', category: CardCategory.PERSONALITY, options: ['İyimser', 'Gerçekçi', 'Karamsar', 'Değişken'] },
    { questionTR: 'Hayalperest misin?', category: CardCategory.PERSONALITY, options: ['Çok', 'Biraz', 'Gerçekçi', 'Hiç'] },
    { questionTR: 'Yaratıcılık?', category: CardCategory.PERSONALITY, options: ['Çok yaratıcı', 'Ortalamanın üstü', 'Normal', 'Pek değil'] },
    { questionTR: 'Analitik mi, sezgisel mi?', category: CardCategory.PERSONALITY, options: ['Analitik', 'Sezgisel', 'Dengeli', 'Duruma göre'] },
    { questionTR: 'Mantık mı, duygu mu?', category: CardCategory.PERSONALITY, options: ['Mantık', 'Duygu', 'Dengeli', 'Duruma göre'] },
    { questionTR: 'Meraklı mısın?', category: CardCategory.PERSONALITY, options: ['Çok meraklı', 'Normal', 'Az', 'Pek değil'] },
    { questionTR: 'Yeni şeyler öğrenme?', category: CardCategory.PERSONALITY, options: ['Çok severim', 'Güzel', 'Gerekince', 'Pek değil'] },
    { questionTR: 'Hata yapmaktan korkar mısın?', category: CardCategory.PERSONALITY, options: ['Hiç', 'Biraz', 'Evet', 'Çok'] },
    { questionTR: 'Karar verdikten sonra?', category: CardCategory.PERSONALITY, options: ['Kararlıyım', 'Bazen şüphe', 'Sık değiştiririm', 'Hep pişman'] },
    { questionTR: 'Baskı altında performansın?', category: CardCategory.PERSONALITY, options: ['Daha iyi', 'Normal', 'Düşer', 'Çökerim'] },
    { questionTR: 'Multitasking?', category: CardCategory.PERSONALITY, options: ['Çok başarılı', 'İdare eder', 'Zorlanırım', 'Yapamam'] },
    { questionTR: 'Dikkat süresi?', category: CardCategory.PERSONALITY, options: ['Çok uzun', 'Normal', 'Kısa', 'Çok kısa'] },
    { questionTR: 'Erteleme eğilimi?', category: CardCategory.PERSONALITY, options: ['Hiç', 'Bazen', 'Sık sık', 'Kronik'] },
    { questionTR: 'Düzenli misin?', category: CardCategory.PERSONALITY, options: ['Çok düzenli', 'Genelde', 'Düzensiz', 'Kaotik'] },
    { questionTR: 'Zamanında mısın?', category: CardCategory.PERSONALITY, options: ['Her zaman', 'Genelde', 'Bazen geç', 'Hep geç'] },
    { questionTR: 'Sözünde durur musun?', category: CardCategory.PERSONALITY, options: ['Kesinlikle', 'Genelde', 'Bazen zorlanırım', 'Pek değil'] },
    
    // ==================== HUMOR (200) ====================
    { questionTR: 'Mizah anlayışın?', category: CardCategory.HUMOR, options: ['Kara mizah', 'Absürt', 'Kelime oyunları', 'Fiziksel komedi'] },
    { questionTR: 'En çok neye gülersin?', category: CardCategory.HUMOR, options: ['Günlük saçmalıklar', 'Stand-up', 'Arkadaş esprileri', 'Kedi videoları'] },
    { questionTR: 'Espri yapma stilin?', category: CardCategory.HUMOR, options: ['Sürekli espri', 'Doğru zamanda', 'Nadiren', 'Dinlerim'] },
    { questionTR: 'Komik bulmadığın mizah?', category: CardCategory.HUMOR, options: ['Aşağılayıcı', 'Kaba küfürlü', 'Çok karanlık', 'Fark etmez'] },
    { questionTR: 'Beraber gülmek?', category: CardCategory.HUMOR, options: ['Çok önemli', 'Güzel', 'Olmasa da olur', 'Önemli değil'] },
    { questionTR: 'Ciddi biri misin?', category: CardCategory.HUMOR, options: ['Hiç', 'Bazen', 'Genelde', 'Çok ciddi'] },
    { questionTR: 'Kendine gülebilir misin?', category: CardCategory.HUMOR, options: ['Her zaman', 'Genelde', 'Zor', 'Hiç'] },
    { questionTR: 'Şaka kaldırır mısın?', category: CardCategory.HUMOR, options: ['Evet', 'Çoğunu', 'Bazılarını', 'Alınırım'] },
    { questionTR: 'Komedi filmi mi, dram mı?', category: CardCategory.HUMOR, options: ['Komedi', 'Dram', 'İkisi de', 'Aksiyon'] },
    { questionTR: 'Stand-up komedyen?', category: CardCategory.HUMOR, options: ['Cem Yılmaz', 'Hasan Can Kaya', 'Yabancı', 'İzlemem'] },
    { questionTR: 'Sitcom severim?', category: CardCategory.HUMOR, options: ['Friends', 'HIMYM', 'The Office', 'Hiçbiri'] },
    { questionTR: 'Türk komedi?', category: CardCategory.HUMOR, options: ['Yılmaz Erdoğan', 'Ata Demirer', 'Şahan', 'Hiçbiri'] },
    { questionTR: 'Internet esprisi?', category: CardCategory.HUMOR, options: ['Meme', 'Tweet', 'Video', 'Anlamam'] },
    { questionTR: 'Kahkaha attıran?', category: CardCategory.HUMOR, options: ['Beklenmedik şeyler', 'Zeka', 'Absürtlük', 'Taklit'] },
    { questionTR: 'Gülmekten ağlar mısın?', category: CardCategory.HUMOR, options: ['Sık sık', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Gece sohbeti?', category: CardCategory.HUMOR, options: ['Derin konuşma', 'Saçmalama', 'İkisi de', 'Uyumak isterim'] },
    { questionTR: 'Troll müsün?', category: CardCategory.HUMOR, options: ['Profesyonel', 'Bazen', 'Pek değil', 'Asla'] },
    { questionTR: 'Argo kullanır mısın?', category: CardCategory.HUMOR, options: ['Çok', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Taklitçilik?', category: CardCategory.HUMOR, options: ['Çok iyiyim', 'İdare eder', 'Beceremem', 'İlgim yok'] },
    { questionTR: 'Espri zamanlaması?', category: CardCategory.HUMOR, options: ['Mükemmel', 'İyi', 'Geliştiriyorum', 'Kötü'] },
    { questionTR: 'Fıkra anlatır mısın?', category: CardCategory.HUMOR, options: ['Çok iyi', 'Denerim', 'Beceriksizim', 'Hiç'] },
    { questionTR: 'Sarkazm?', category: CardCategory.HUMOR, options: ['Ana dilim', 'Kullanırım', 'Anlarım', 'Hiç'] },
    { questionTR: 'İroni?', category: CardCategory.HUMOR, options: ['Çok severim', 'Kullanırım', 'Bazen', 'Pek anlamam'] },
    { questionTR: 'Parodi?', category: CardCategory.HUMOR, options: ['Bayılırım', 'Eğlenceli', 'Bazen', 'Pek değil'] },
    { questionTR: 'Kahkahanla uyandırır mısın?', category: CardCategory.HUMOR, options: ['Evet, çok gülerim', 'Bazen', 'Sessiz gülerim', 'Hayır'] },
    { questionTR: 'Yüz ifadelerin?', category: CardCategory.HUMOR, options: ['Çok belli', 'Normal', 'Poker face', 'Kontrol altında'] },
    { questionTR: 'Çizgi film?', category: CardCategory.HUMOR, options: ['Çok severim', 'Nostalji', 'Çocukça', 'Hiç'] },
    { questionTR: 'Animasyon film?', category: CardCategory.HUMOR, options: ['Pixar hayranı', 'Severim', 'Bazen', 'Çocuklar için'] },
    { questionTR: 'Korku-komedi?', category: CardCategory.HUMOR, options: ['En iyisi', 'İlginç', 'Kararsız', 'Pek değil'] },
    { questionTR: 'Romantik komedi?', category: CardCategory.HUMOR, options: ['Bayılırım', 'Tatlı', 'Klişe', 'Sıkıcı'] },
    { questionTR: 'Skeç/kısa video?', category: CardCategory.HUMOR, options: ['Her gün izlerim', 'Severim', 'Bazen', 'İlgim yok'] },
    { questionTR: 'Vine/TikTok komedisi?', category: CardCategory.HUMOR, options: ['Favorim', 'Eğlenceli', 'Bazen', 'Kalitesiz'] },
    { questionTR: 'Improv/doğaçlama?', category: CardCategory.HUMOR, options: ['Çok yetenekliyim', 'İyiyim', 'Zorlanırım', 'Yapamam'] },
    { questionTR: 'Komedi podcast?', category: CardCategory.HUMOR, options: ['Dinlerim', 'Bazen', 'Nadiren', 'Hiç'] },
    { questionTR: 'Esprili flört?', category: CardCategory.HUMOR, options: ['Tek yolum', 'Severim', 'Biraz', 'Ciddi olurum'] },
    { questionTR: 'Awkward anlar?', category: CardCategory.HUMOR, options: ['Çok komik', 'Utanırım', 'Kaçarım', 'Fark etmem'] },
    { questionTR: 'Yanlış anlama sonrası?', category: CardCategory.HUMOR, options: ['Gülerim', 'Açıklarım', 'Utanırım', 'Kızarım'] },
    { questionTR: 'Dad jokes?', category: CardCategory.HUMOR, options: ['Ustayım', 'Severim', 'Çekilmez', 'Anlamam'] },
    { questionTR: 'Prank/şaka?', category: CardCategory.HUMOR, options: ['Yaparım', 'Zararsızsa', 'Sevmem', 'Kızarım'] },
    { questionTR: 'Kendi esprine güler misin?', category: CardCategory.HUMOR, options: ['Hep gülerim', 'Bazen', 'Nadiren', 'Hiç'] },
    
    // ==================== DATING/ROMANCE (200) ====================
    { questionTR: 'İlk buluşmada nereye gidelim?', category: CardCategory.VALUES, options: ['Kafe', 'Restoran', 'Park yürüyüşü', 'Bar'] },
    { questionTR: 'İdeal buluşma süresi?', category: CardCategory.VALUES, options: ['1-2 saat', '2-3 saat', 'Akşama kadar', 'Sınırsız'] },
    { questionTR: 'İlk mesajda ne bekliyorsun?', category: CardCategory.VALUES, options: ['Kreatif giriş', 'Samimi selam', 'Soru', 'Espri'] },
    { questionTR: 'Mesajlaşma sıklığı?', category: CardCategory.VALUES, options: ['Sürekli', 'Günde birkaç', 'Günlük', 'Gerektiğinde'] },
    { questionTR: 'Sesli mesaj mı, yazılı mı?', category: CardCategory.VALUES, options: ['Sesli', 'Yazılı', 'İkisi de', 'Fark etmez'] },
    { questionTR: 'Görüntülü arama?', category: CardCategory.VALUES, options: ['Severim', 'Ara sıra', 'Pek değil', 'Asla'] },
    { questionTR: 'Telefonda konuşmak?', category: CardCategory.VALUES, options: ['Çok severim', 'İyi', 'Kısa tutarım', 'Mesaj tercih'] },
    { questionTR: 'Flört hızı?', category: CardCategory.VALUES, options: ['Hızlı', 'Orta', 'Yavaş', 'Doğal akış'] },
    { questionTR: 'Fiziksel temas?', category: CardCategory.VALUES, options: ['Önemli', 'Güzel', 'Yavaş yavaş', 'Dikkatli'] },
    { questionTR: 'El ele tutuşmak ne zaman?', category: CardCategory.VALUES, options: ['İlk buluşma', 'Birkaç buluşma', 'Ciddi olunca', 'Kendiliğinden'] },
    { questionTR: 'İlk öpücük ne zaman?', category: CardCategory.VALUES, options: ['İlk buluşma', 'Birkaç buluşma', 'Resmi olunca', 'Kendiliğinden'] },
    { questionTR: 'Love language?', category: CardCategory.VALUES, options: ['Dokunmak', 'Sözler', 'Hediyeler', 'Kaliteli zaman'] },
    { questionTR: 'Hediye vermek?', category: CardCategory.VALUES, options: ['Sık sık', 'Özel günlerde', 'Nadiren', 'Tercih etmem'] },
    { questionTR: 'Hediye almak?', category: CardCategory.VALUES, options: ['Bayılırım', 'Güzel', 'Utandırır', 'Gerek yok'] },
    { questionTR: 'Sürpriz planlama?', category: CardCategory.VALUES, options: ['Çok yaparım', 'Bazen', 'Pek değil', 'Sevmem'] },
    { questionTR: 'Romantik akşam yemeği?', category: CardCategory.VALUES, options: ['Hayalim', 'Güzel', 'Arada', 'Abartılı'] },
    { questionTR: 'Evde akşam mı, dışarıda mı?', category: CardCategory.VALUES, options: ['Evde', 'Dışarıda', 'Dengeli', 'Fark etmez'] },
    { questionTR: 'Film gecesi?', category: CardCategory.VALUES, options: ['Her hafta', 'Sık sık', 'Bazen', 'Nadiren'] },
    { questionTR: 'Birlikte yemek yapmak?', category: CardCategory.VALUES, options: ['Çok romantik', 'Eğlenceli', 'Karışık', 'Ben yapmam'] },
    { questionTR: 'Sabah kahvesi birlikte?', category: CardCategory.VALUES, options: ['Şart', 'Güzel', 'Bazen', 'Sabah konuşmam'] },
    { questionTR: 'Özel günleri kutlama?', category: CardCategory.VALUES, options: ['Çok önemli', 'Evet', 'Basit', 'Gereksiz'] },
    { questionTR: 'Yıldönümü?', category: CardCategory.VALUES, options: ['Büyük kutlama', 'Özel bir şey', 'Basit', 'Unuturum'] },
    { questionTR: 'Sevgililer Günü?', category: CardCategory.VALUES, options: ['Çok önemli', 'Kutlarım', 'Basit', 'Ticari'] },
    { questionTR: 'Sosyal medyada paylaşım?', category: CardCategory.VALUES, options: ['Sürekli', 'Bazen', 'Özel günlerde', 'Hiç'] },
    { questionTR: 'Partner fotoğrafı profilde?', category: CardCategory.VALUES, options: ['Evet', 'Belki', 'Hayır', 'Fark etmez'] },
    { questionTR: 'Çift hesabı?', category: CardCategory.VALUES, options: ['Tatlı', 'Garip', 'Asla', 'Düşünürüm'] },
    { questionTR: 'Eşleşen kıyafetler?', category: CardCategory.VALUES, options: ['Tatlı', 'Arada', 'Cringe', 'Asla'] },
    { questionTR: 'Takma isim/nickname?', category: CardCategory.VALUES, options: ['Şart', 'Tatlı', 'Bazen', 'Gereksiz'] },
    { questionTR: 'Günlük iltifat?', category: CardCategory.VALUES, options: ['Bekliyorum', 'Güzel olur', 'Gerekli değil', 'Yapay gelir'] },
    { questionTR: 'Partnerle spor?', category: CardCategory.VALUES, options: ['Motivasyon', 'Eğlenceli', 'Ayrı daha iyi', 'Spor yapmam'] },
    { questionTR: 'Partnerle oyun?', category: CardCategory.VALUES, options: ['Rekabetçi', 'Eğlenceli', 'Bazen', 'Oyun oynamam'] },
    { questionTR: 'Birlikte kitap okumak?', category: CardCategory.VALUES, options: ['Romantik', 'Güzel', 'Kendi kitabım', 'Okumam'] },
    { questionTR: 'Aynı diziyi izlemek?', category: CardCategory.VALUES, options: ['Şart', 'Güzel', 'Bazen ayrı', 'Kendi zevklerim'] },
    { questionTR: 'Müzik zevki uyumu?', category: CardCategory.VALUES, options: ['Çok önemli', 'Güzel olur', 'Fark etmez', 'Önemli değil'] },
    { questionTR: 'Birlikte konsere gitmek?', category: CardCategory.VALUES, options: ['Hayalim', 'Eğlenceli', 'Bazen', 'Sevmem'] },
    { questionTR: 'Tatil planı beraber mi?', category: CardCategory.VALUES, options: ['Her zaman', 'Çoğunlukla', 'Bazen ayrı', 'Ayrı daha iyi'] },
    { questionTR: 'Ailelerin tanışması?', category: CardCategory.VALUES, options: ['Erken', 'Ciddi olunca', 'Geç', 'Gerek yok'] },
    { questionTR: 'Arkadaş grubuyla tanışma?', category: CardCategory.VALUES, options: ['Hemen', 'Biraz sonra', 'Ciddi olunca', 'Ayrı tutarım'] },
    { questionTR: 'Ortak arkadaş?', category: CardCategory.VALUES, options: ['Güzel', 'Olabilir', 'Karışık', 'İstemem'] },
    { questionTR: 'Exlerle ilişki?', category: CardCategory.VALUES, options: ['Arkadaş olabilir', 'Mesafeli', 'İletişim yok', 'Duruma göre'] },
    { questionTR: 'Partnerim arkadaşımla konuşsun mu?', category: CardCategory.VALUES, options: ['Tabii', 'Normal sınırlarda', 'Dikkatli', 'İstemem'] },
    { questionTR: 'Kıskançlık gösterisi?', category: CardCategory.VALUES, options: ['Tatlı', 'Sınırlı', 'Rahatsız edici', 'Güven eksikliği'] },
    { questionTR: 'Partner başkasına bakarsa?', category: CardCategory.VALUES, options: ['Normal', 'Biraz rahatsız', 'Kıskanırım', 'Sorun'] },
    { questionTR: 'Geçmiş ilişkileri konuşmak?', category: CardCategory.VALUES, options: ['Açıkça', 'Genel hatlarıyla', 'Minimal', 'Hiç'] },
    { questionTR: 'Kaç tane ciddi ilişki?', category: CardCategory.VALUES, options: ['0', '1-2', '3-5', '5+'] },
    { questionTR: 'En uzun ilişkin?', category: CardCategory.VALUES, options: ['6 aydan az', '6ay-2 yıl', '2-5 yıl', '5+ yıl'] },
    { questionTR: 'Ayrılık nedenleri?', category: CardCategory.VALUES, options: ['Uyumsuzluk', 'Aldatma', 'Mesafe', 'Aileler'] },
    { questionTR: 'Ayrılık sonrası toparlanma?', category: CardCategory.VALUES, options: ['Hızlı', 'Normal', 'Uzun', 'Çok uzun'] },
  ];

  await prisma.card.deleteMany();
  console.log('Old cards deleted...');
  
  await prisma.card.createMany({
    data: cards.map((c) => ({
      questionTR: c.questionTR,
      category: c.category,
      optionsJson: JSON.stringify(c.options),
    })),
  });

  console.log(`${cards.length} cards created!`);

  // Seed admin
  console.log('Admin user created/updated');
  console.log('Seeding completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
